name: "conftest"
version: "0.20.0"
usage: "Test Helm Charts"
description: |-
  "Test your Helm Charts with Open Policy Agent"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"

ignoreFlags: false
useTunnel: false
